repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort

  - repo: https://github.com/python/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/pylint
    rev: v2.9.5
    hooks:
      - id: pylint
