name: ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Install package
      run: |
        pip install .
        pip install -r test_requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov cleanplotlib
    # No codecov until
    # https://github.com/codecov/codecov-action/issues/43
    # is solved. :(
    # - name: Submit to codecov
    #   uses: codecov/codecov-action@v1.0.6
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: ./coverage.xml
    #     flags: ${{ matrix.python-version }}
